/**
 * Product Entity
 * 
 * This is the DOMAIN LAYER entity representing a beauty product in GLAMGO.
 * It contains all the information needed to display and manage products.
 * 
 * This entity is independent of Firebase or any other implementation detail.
 */

import { ProductCategory } from './ProductCategory';

export interface Product {
  /**
   * Unique identifier for the product
   * Generated by Firestore
   */
  id: string;

  /**
   * Product name (e.g., "Silk Protein Hair Serum")
   */
  name: string;

  /**
   * Detailed product description
   * Markdown or plain text describing features, benefits, usage
   */
  description: string;

  /**
   * Price in USD (e.g., 29.99)
   */
  price: number;

  /**
   * Array of image URLs
   * First image is the primary display image
   * Stored in Firebase Storage or external CDN
   */
  imageUrls: string[];

  /**
   * Product category for filtering and organization
   */
  category: ProductCategory;

  /**
   * ID of the vendor who sells this product
   * References the vendors collection
   */
  vendorId: string;

  /**
   * Display name of the vendor
   * Denormalized for faster display without additional query
   */
  vendorName: string;

  /**
   * Current stock quantity available
   * 0 = out of stock
   */
  stockQuantity: number;

  /**
   * Average rating from customer reviews (0.0 to 5.0)
   * Calculated from all reviews
   */
  averageRating: number;

  /**
   * Total number of reviews for this product
   */
  reviewCount: number;

  /**
   * When the product was first added to the catalog
   */
  createdAt: Date;

  /**
   * When the product was last updated
   */
  updatedAt: Date;

  /**
   * Optional: Brand name (e.g., "GLAMGO Beauty", "Luxe Cosmetics")
   */
  brand?: string;

  /**
   * Optional: Product SKU for inventory management
   */
  sku?: string;

  /**
   * Optional: Weight in ounces for shipping calculations
   */
  weight?: number;

  /**
   * Optional: Featured product flag for homepage display
   */
  isFeatured?: boolean;

  /**
   * Optional: Sale price (if on sale)
   */
  salePrice?: number;
}

/**
 * Type for creating a new product (without generated fields)
 */
export type CreateProductData = Omit<Product, 'id' | 'createdAt' | 'updatedAt' | 'averageRating' | 'reviewCount'>;

/**
 * Type for updating an existing product
 */
export type UpdateProductData = Partial<Omit<Product, 'id' | 'createdAt' | 'updatedAt'>>;
